networks:
  system-pax:
    driver: bridge

volumes:
  db-data:
    driver: local


services:
  postgres:
    image: 'postgres:17.5-alpine'
    ports:
      - '5435:5432'
    env_file:
      - ./system/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 20

  pax-keycloak-postgres:
    image: postgres:17.5-alpine
    container_name: pax-keycloak-postgres
    environment:
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: keycloak
    env_file:
      - ./system/.env
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 20

  pax-keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: pax-keycloak
    command: start-dev --metrics-enabled=true
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      JAVA_OPTS: -Dkeycloak.migration.usersExportStrategy=REALM_FILE
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    depends_on:
      pax-keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/9000"]
      interval: 10s
      timeout: 5s
      retries: 30

  pax-backend:
    build:
      context: ./system
      dockerfile: Dockerfile
    container_name: pax-backend
    ports:
      - "8081:8081"
    env_file:
      - ./system/.env
    environment:
      - SPRING_PROFILES_ACTIVE=deployment
      - HOST=postgres:5432
      - KEYCLOAK_ISSUER_URI=http://pax-keycloak:8080/realms/pax
    depends_on:
      postgres:
        condition: service_healthy
      pax-keycloak:
        condition: service_healthy

  pax-frontend:
    build:
      context: ./frontend/paxfrontend
      dockerfile: Dockerfile
    container_name: pax-frontend
    ports:
      - "80:80"
    depends_on:
      - pax-backend
